version: 0.2
env:
  variables:
    CI: "true"
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm build
      - npm test
artifacts:
  files:
    - './build/**/*'
  base-directory: $CODEBUILD_SRC_DIR
